name: Pull Request WorkFlow

on:
  pull_request:
    branches:
      - master

jobs:
  app-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --ignore-platform-reqs
      - name: Check Code Styles
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
      - name: Execute tests  via PHPUnit
        run: ./vendor/bin/phpunit